version: "3.8"

services:
  compressa-pod:
    image: "compressa/compressa-pod:0.3.2"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS:-all}" ]
            capabilities: [ gpu ]
    shm_size: "12g"
    volumes:
      - "${RESOURCES_PATH:-./resources}:/app/resources:rw"
      - ./deploy-qwen14.json:/configs/deploy.json:ro
    environment:
      MINIO_URL: "minio-s3:9000"
    command: >
      python 
      -m uvicorn manager.app.main:app 
      --host 0.0.0.0 
      --port 5100 
      --root-path /api

  compressa-client-chat:
    image: "compressa/compressa-client-chat:0.3.2"
    environment:
      - COMPRESSA_POD_HOST=http://compressa-pod
      - COMPRESSA_POD_PORT=5000
    command: >
      client/chat/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/chat

  compressa-client-ft:
    image: "compressa/compressa-client-ft:0.3.2"
    environment:
      - COMPRESSA_POD=http://compressa-pod:5100
    command: >
      client/finetune/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/finetune

  aim-server:
    image: "compressa/aim-server:0.3.2"
    volumes:
      - aim-data:/data:rw
    command: >
      /bin/sh -c "echo 'N' | aim init --repo /data &&
      aim server --host 0.0.0.0 --port 53800 -y --repo /data"

  aim-ui:
    image: "compressa/aim-ui:0.3.2"
    depends_on:
      - aim-server
    volumes:
      - aim-data:/data:rw
    command: >
      /bin/sh -c "echo 'N' | aim init --repo /data &&
      aim up --host 0.0.0.0 --port 43800 --workers 2 --repo /data --base-path aim-ui"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - compressa-client-chat
      - compressa-client-ft
      - compressa-pod
      - aim-ui
      - aim-server
      - auth

  minio-s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data

  auth:
    image: compressa/compressa-auth:0.3.2
    volumes:
      - ./tokens/user.csv:/tokens/user.csv:ro
      - ./tokens/admin.csv:/tokens/admin.csv:ro

volumes:
  minio_data:
  aim-data: