version: "3.8"

services:
  compressa-api-nginx:
    image: nginx:stable-alpine3.19-slim
    ports:
      - "5555:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - compressa-client-chat
      - compressa-infinity-rerank
      - compressa-pod-1
      - compressa-pod-2
    networks:
      - compresa-network

  compressa-pod-1:
    image: "compressa/compressa-pod:latest"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_CHAT:-0}" ]
            capabilities: [ gpu ]
    volumes:
      - "compressa-data:/app/resources:rw"
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
    command: >
      python3 -m uvicorn manager.app.main:app --host 0.0.0.0 --port 5100 --root-path /pod-1/api

  compressa-pod-2:
    image: "compressa/compressa-pod:latest"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_EMB:-1}" ]
            capabilities: [ gpu ]
    volumes:
      - "compressa-data:/app/resources:rw"
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
    command: >
      python3 -m uvicorn manager.app.main:app --host 0.0.0.0 --port 5100 --root-path /pod-2/api

  compressa-infinity-rerank:
    image: "michaelf34/infinity:0.0.51"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_RERANK:-1}" ]
            capabilities: [ gpu ]
    environment:
      - HF_HOME=/app/resources/rerank-cache
    volumes:
      - "compressa-data:/app/resources:rw"
    networks:
      - compresa-network
    command: >
      v2
      --model-id ${RERANK_MODEL_1}
      --served-model-name Compressa-ReRank
      --port 80
      --proxy-root-path /v1

  compressa-client-chat:
    image: "compressa/compressa-client-chat:latest"
    environment:
      - COMPRESSA_POD_HOST=http://compressa-pod-1
      - COMPRESSA_POD_PORT=5000
    command: >
      client/chat/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/chat
    networks:
      - compresa-network

  minio-s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    networks:
      - compresa-network

networks:
  compresa-network:
    external: true
    name: compressa-network

volumes:
  minio-data:
  compressa-data:
    driver: local
    driver_opts:
      type: none
      device: ${RESOURCES_PATH:-./data/compressa}
      o: bind
