version: "3.8"

services:
  dispatcher:
    image: compressa/compressa-entrypoint:0.3.9
    environment:
      - COMPRESSA_API_KEY=${COMPRESSA_API_KEY:-COMPRESSA_API_KEY}
      - RESOURCES_PATH=${RESOURCES_PATH}
      - HF_HOME=${HF_HOME}
      - DISPATCHER_HOST=${DISPATCHER_HOST:-central-pod}
      - DISPATCHER_PORT=${DISPATCHER_PORT:-8001}
      - AUTODEPLOY=${AUTODEPLOY:-True}
      - POD_NAME=${POD_NAME:-compressa-pod}
    ports:
      - "${DISPATCHER_PORT:-8001}:${DISPATCHER_PORT:-8001}"
    restart: on-failure
    volumes:
      - ./build:${CFG_DIR:-/app/deploy}
      - ./build:${WORKDIR:-/app/workdir}
      - "${RESOURCES_PATH:-./resources}:/app/resources:rw"
    container_name: ${DISPATCHER_HOST:-dispatcher}
    networks:
      - "${NETWORK:-common_network}"

    command: python -m main_entry
    stdin_open: true
    tty: true

  compressa-client-chat:
    image: "compressa/compressa-ui:0.3.9"
    container_name: compressa-client-chat
    environment:
      - COMPRESSA_POD=http://nginx:80
    command: >
      client/chat/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/chat
    networks:
      - "${NETWORK:-common_network}"
    restart: always

  compressa-client-ft:
    image: "compressa/compressa-ui:0.3.9"
    container_name: compressa-client-ft
    environment:
      - COMPRESSA_POD=http://nginx:80/api/chat
    command: >
      client/finetune/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/finetune
    networks:
      - "${NETWORK:-common_network}"
    restart: always

  compressa-client-layout:
    image: "compressa/compressa-ui:0.3.9"
    container_name: compressa-client-layout
    environment:
      - COMPRESSA_LAYOUT=http://compressa-layout:8000/general/v0/general
    command: >
      client/layout/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/layout
    networks:
      - "${NETWORK:-common_network}"
    restart: always

  minio-s3:
    image: quay.io/minio/minio
    container_name: minio-s3
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    networks:
      - "${NETWORK:-common_network}"
    restart: always

  compressa-layout:
    image: "compressa/compressa-layout:0.3.9"
    networks:
      -  "${NETWORK:-common_network}"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - compressa-client-chat
      - compressa-client-layout
      - dispatcher
    networks:
      - "${NETWORK:-common_network}"
    restart: always

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Rjvghtccf@1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${RESOURCES_PATH}/opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - "${NETWORK:-common_network}"

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - "${NETWORK:-common_network}"

  data-prepper:
    image: opensearchproject/data-prepper:2.6.0
    container_name: data-prepper
    volumes:
      - "${DATA_PREPPER_CFG_PATH:-../../services/elk/data-prepper/}/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml:ro"
      - "${DATA_PREPPER_CFG_PATH:-../../services/elk/data-prepper/}/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml:ro"
    ports:
      - "2021:2021"
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - "${NETWORK:-common_network}"

    
  auth:
    image: compressa/compressa-auth:0.3.9
    container_name: compressa-auth
    volumes:
      - ./tokens/user.csv:/tokens/user.csv:ro
      - ./tokens/admin.csv:/tokens/admin.csv:ro
    networks:
      - "${NETWORK:-common_network}"
    restart: always


networks:
  common_network:
    external: true

volumes:
  minio-data:
  compressa-data:
    driver: local
    driver_opts:
      type: none
      device: ${RESOURCES_PATH:-./data/compressa}
      o: bind 
  opensearch-data:

