services:
  compressa-pod:
    image: "compressa/compressa-pod:0.3.8"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS:-all}" ]
            capabilities: [ gpu ]
    shm_size: "32g"
    volumes:
      - "${RESOURCES_PATH:-./resources}:/app/resources:rw"
      - ./deploy-qwen14.json:/configs/deploy.json:ro
    environment:
      MINIO_URL: "minio-s3:9000"
      ROOT_PATH: "/api"
    restart: always

  compressa-client-chat:
    image: "compressa/compressa-ui:0.3.8"
    environment:
      - COMPRESSA_POD=http://nginx:80
    command: >
      client/chat/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/chat
    restart: always

  compressa-client-ft:
    image: "compressa/compressa-ui:0.3.8"
    environment:
      - COMPRESSA_POD=http://nginx:80/api
    command: >
      client/finetune/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/finetune
    restart: always

  aim-server:
    image: "compressa/aim-server:0.3.8"
    # volumes:
    #   - aim-data:/data:rw
    command: >
      /bin/sh -c "echo 'N' | aim init --repo /data &&
      aim server --host 0.0.0.0 --port 53800 -y --repo /data"
    restart: always

  aim-ui:
    image: "compressa/aim-ui:0.3.8"
    depends_on:
      - aim-server
    # volumes:
    #   - aim-data:/data:rw
    command: >
      /bin/sh -c "echo 'N' | aim init --repo /data &&
      aim up --host 0.0.0.0 --port 43800 --workers 2 --repo /data --base-path aim-ui"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - compressa-client-chat
      - compressa-client-ft
      - compressa-pod
      - aim-ui
      - aim-server
      - auth
    restart: always

  minio-s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    restart: always

  auth:
    image: compressa/compressa-auth:0.3.8
    volumes:
      - ./tokens/user.csv:/tokens/user.csv:ro
      - ./tokens/admin.csv:/tokens/admin.csv:ro
    restart: always

volumes:
  minio_data:
  # aim-data: