version: "3.8"

services:
  compressa-pod:
    image: "compressa/compressa-pod:latest"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS:-all}" ]
            capabilities: [ gpu ]
    ports:
      - "5100:5100"
    volumes:
      - "${RESOURCES_PATH:-./resources}:/app/resources:rw"
    environment:
      MINIO_URL: "minio-s3:9000"
    command: >
      python3.9 -m uvicorn manager.app.main:app --host 0.0.0.0 --port 5100 --root-path /api

  compressa-client-chat:
    image: "compressa/compressa-client-chat:latest"
    environment:
      - COMPRESSA_POD_HOST=http://compressa-pod
      - COMPRESSA_POD_PORT=5000
    command: >
      client/chat/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/chat

  compressa-client-ft:
    image: "compressa/compressa-client-ft:latest"
    environment:
      - COMPRESSA_POD=http://compressa-pod:5100
    command: >
      client/finetune/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/finetune

  aim-server:
    image: "compressa/aim-server:latest"
    volumes:
      - aim-data:/data:rw
    ports:
      - "53800:53800"
      - "53801:53801"
      - "53802:53802"
    command: >
      /bin/sh -c "echo 'N' | aim init --repo /data &&
      aim server --host 0.0.0.0 --port 53800 --workers 2 --repo /data"

  aim-ui:
    image: "compressa/aim-ui:latest"
    depends_on:
      - aim-server
    volumes:
      - aim-data:/data:rw
    ports:
      - "43800:43800"
    command: >
      /bin/sh -c "echo 'N' | aim init --repo /data &&
      aim up --host 0.0.0.0 --port 43800 --workers 2 --repo /data --base-path aim-ui"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - compressa-client-chat
      - compressa-client-ft
      - compressa-pod
      - aim-ui
      - aim-server

  minio-s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  minio_data:
  aim-data: