services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - compressa-client-chat
      - compressa-client-layout
      - compressa-pod-1
      - compressa-pod-2
      - compressa-pod-3
      - compressa-pod-4
      - compressa-pod-5
      - auth
    networks:
      - compresa-network
    restart: always

  compressa-pod-1:
    image: "compressa/compressa-pod:0.3.8"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_1:-0}" ]
            capabilities: [ gpu ]
    shm_size: "32g"
    volumes:
      - compressa-data:/app/resources:rw
      - ./deploy-llm.json:/configs/deploy.json:ro
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
      ROOT_PATH: "/api/chat"
    restart: always

  compressa-pod-2:
    image: "compressa/compressa-pod:0.3.8"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_2:-1}" ]
            capabilities: [ gpu ]
    shm_size: "32g"
    volumes:
      - compressa-data:/app/resources:rw
      - ./deploy-embeddings.json:/configs/deploy.json:ro
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
      ROOT_PATH: "/api/embeddings"
    restart: always

  compressa-pod-3:
    image: "compressa/compressa-pod:0.3.8"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_2:-1}" ]
            capabilities: [ gpu ]
    shm_size: "32g"
    volumes:
      - compressa-data:/app/resources:rw
      - ./deploy-rerank.json:/configs/deploy.json:ro
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
      ROOT_PATH: "/api/rerank"
    restart: always

  compressa-pod-4:
    image: "compressa/compressa-pod:0.3.8"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_2:-1}" ]
            capabilities: [ gpu ]
    shm_size: "32g"
    volumes:
      - compressa-data:/app/resources:rw
      - ./deploy-tts.json:/configs/deploy.json:ro
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
      ROOT_PATH: "/api/tts"
    restart: always

  compressa-pod-5:
    image: "compressa/compressa-pod:0.3.8"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_2:-1}" ]
            capabilities: [ gpu ]
    shm_size: "32g"
    volumes:
      - compressa-data:/app/resources:rw
      - ./deploy-asr.json:/configs/deploy.json:ro
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
      ROOT_PATH: "/api/asr"
    restart: always

  compressa-client-chat:
    image: "compressa/compressa-ui:0.3.8"
    environment:
      - COMPRESSA_POD=http://nginx:80
    command: >
      client/chat/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/chat
    networks:
      - compresa-network
    restart: always

  compressa-client-ft:
    image: "compressa/compressa-ui:0.3.8"
    environment:
      - COMPRESSA_POD=http://nginx:80/api/chat
    command: >
      client/finetune/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/finetune
    networks:
      - compresa-network
    restart: always

  compressa-client-layout:
    image: "compressa/compressa-ui:0.3.8"
    environment:
      - COMPRESSA_LAYOUT=http://compressa-layout:8000/general/v0/general
    command: >
      client/layout/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/layout
    networks:
      - compresa-network
    restart: always

  minio-s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    networks:
      - compresa-network
    restart: always

  auth:
    image: compressa/compressa-auth:0.3.8
    volumes:
      - ./tokens/user.csv:/tokens/user.csv:ro
      - ./tokens/admin.csv:/tokens/admin.csv:ro
    networks:
      - compresa-network
    restart: always

  compressa-layout:
    image: "compressa/compressa-layout:0.3.8"
    networks:
      - compresa-network

networks:
  compresa-network:

volumes:
  minio-data:
  compressa-data:
    driver: local
    driver_opts:
      type: none
      device: ${RESOURCES_PATH:-./data/compressa}
      o: bind 
