version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine3.19-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - compressa-client-chat
      - compressa-client-layout
      - compressa-rerank
      - compressa-pod-1
      - compressa-pod-2
      - auth
    networks:
      - compresa-network

  compressa-pod-1:
    image: "compressa/compressa-pod:0.3.2"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_1:-0}" ]
            capabilities: [ gpu ]
    volumes:
      - compressa-data:/app/resources:rw
      - ./deploy-qwen14.json:/configs/deploy.json:ro
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
    command: >
      python3
        -m uvicorn manager.app.main:app
        --host 0.0.0.0
        --port 5100
        --root-path /api/chat

  compressa-pod-2:
    image: "compressa/compressa-pod:0.3.2"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_2:-1}" ]
            capabilities: [ gpu ]
    volumes:
      - compressa-data:/app/resources:rw
      - ./deploy-embeddings.json:/configs/deploy.json:ro
    networks:
      - compresa-network
    environment:
      MINIO_URL: "minio-s3:9000"
    command: >
      python3
        -m uvicorn manager.app.main:app
        --host 0.0.0.0
        --port 5100
        --root-path /api/embeddings

  compressa-rerank:
    image: "compressa/compressa-rerank:0.3.2"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: [ "${DOCKER_GPU_IDS_2:-1}" ]
            capabilities: [ gpu ]
    environment:
      - HF_HOME=/app/resources/rerank-cache
    volumes:
      - "compressa-data:/app/resources:rw"
    networks:
      - compresa-network
    command: >
      v2
      --model-id ${RERANK_MODEL_1}
      --served-model-name Compressa-ReRank
      --port 80
      --proxy-root-path /v1

  compressa-layout:
    image: "compressa/compressa-layout:0.3.2"
    networks:
      - compresa-network

  compressa-client-chat:
    image: "compressa/compressa-client-chat:0.3.2"
    environment:
      - COMPRESSA_POD_HOST=http://compressa-pod-1
      - COMPRESSA_POD_PORT=5000
    command: >
      client/chat/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/chat
    networks:
      - compresa-network

  compressa-client-layout:
    image: "compressa/compressa-client-layout:0.3.2"
    environment:
      - COMPRESSA_LAYOUT=http://compressa-layout:8000/general/v0/general
    command: >
      client/layout/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=/layout
    networks:
      - compresa-network

  minio-s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    networks:
      - compresa-network

  auth:
    image: compressa/compressa-auth:0.3.2
    volumes:
      - ./tokens/user.csv:/tokens/user.csv:ro
      - ./tokens/admin.csv:/tokens/admin.csv:ro
    networks:
      - compresa-network

networks:
  compresa-network:

volumes:
  minio-data:
  compressa-data:
    driver: local
    driver_opts:
      type: none
      device: ${RESOURCES_PATH:-./data/compressa}
      o: bind
