{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "compressa-platform.fullname" . }}-ingress
  labels:
    {{- include "compressa-platform.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range $name, $spec := .Values.worker.instances }}
          {{- include "compressa-platform.ingress-paths" (dict "name" $name "top" $ "spec" .) | nindent 10 }}
          {{- end }}
          {{- include "compressa-platform.ingress-paths" (dict "name" "rerank" "top" $ "spec" .Values.rerank) | nindent 10 }}
          {{- include "compressa-platform.ingress-paths" (dict "name" "layout" "top" $ "spec" .Values.layout) | nindent 10 }}
          {{- range $name, $spec := .Values.client.instances }}
          {{- include "compressa-platform.ingress-paths" (dict "name" $name "top" $ "spec" $spec) | nindent 10 }}
          {{- end }}
{{- end }}
